---
applications:
- name: rubytomongo
  memory: 128M
  instances: 1
  host: rubytomongo
  domain: apps.ccng-dev.net
  path: .
  buildpack: https://github.com/cloudfoundry/heroku-buildpack-ruby
  services:
    rubytomongodb20:
      label: mongodb
      provider: core
      version: '2.2'
      plan: free
