#- name: "dotnetwithmongo"
#  framework: ".Net"
#  service: "MongoDB"
#- name: "dotnetwithmssql"
#  framework: ".Net"
#  service: "MS SQL Server"
#- name: "dotnetwithmysql"
#  framework: ".Net"
#  service: "MySQL"
#- name: "dotnetwithpostgre"
#  framework: ".Net"
#  service: "PostgreSQL"
#- name: "dotnetwithrabbit"
#  framework: ".Net"
#  service: "RabbitMQ"
#- name: "dotnetwithuhurufs"
#  framework: ".Net"
#  service: "UhuruFS"
#- name: "javawithmongo"
#  framework: "Java"
#  service: "MongoDB"
#- name: "javawithrabbit"
#  framework: "Java"
#  service: "RabbitMQ"
- name: "javawithredis"
  framework: "Java"
  service: "Redis"
#- name: "nodejsmongo"
#  framework: "node.js"
#  service: "MongoDB"
- name: "nodejswithmysql"
  framework: "node.js"
  service: "MySQL"
#- name: "phpwithmssql"
#  framework: "PHP"
#  service: "MS SQL Server"
#- name: "phpwithmysql"
#  framework: "PHP"
#  service: "MySQL"
#- name: "phpwithuhurufs"
#  framework: "PHP"
#  service: "UhuruFS"
#- name: "rubywithmongo"
#  framework: "Ruby"
#  service: "MongoDB"
- name: "rubywithmysql"
  framework: "Ruby"
  service: "MySQL"
