#- name: "dotnetwithmssql"
#  framework: ".Net"
#  service: "MS SQL Server"
- name: "dotnetwithmysql"
  framework: ".Net"
  service: "MySQL"
#- name: "dotnetwithpostgre"
#  framework: ".Net"
#  service: "PostgreSQL"
#- name: "dotnetwithrabbit"
#  framework: ".Net"
#  service: "RabbitMQ"
- name: "dotnetwithredis"
  framework: ".Net"
  service: "Redis"
#- name: "javawithmssql"
#  framework: "Java"
#  service: "MS SQL Server"
#- name: "javawithmysql"
#  framework: "Java"
#  service: "MySQL"
#- name: "javawithpostgre"
#  framework: "Java"
#  service: "PostgreSQL"
#- name: "javawithrabbit"
#  framework: "Java"
#  service: "RabbitMQ"
- name: "javawithredis"
  framework: "Java"
  service: "Redis"
#- name: "nodejswithmssql"
#  framework: "node.js"
#  service: "MS SQL Server"
- name: "nodejswithmysql"
  framework: "node.js"
  service: "MySQL"
#- name: "nodejswithpostgre"
#  framework: "node.js"
#  service: "PostgreSQL"
#- name: "nodejswithrabbit"
#  framework: "node.js"
#  service: "RabbitMQ"
#- name: "nodejswithredis"
#  framework: "node.js"
#  service: "Redis"
#- name: "rubywithmssql"
#  framework: "Ruby"
#  service: "MS SQL Server"
- name: "rubywithmysql"
  framework: "Ruby"
  service: "MySQL"
#- name: "rubywithpostgre"
#  framework: "Ruby"
#  service: "PostgreSQL"
#- name: "rubywithrabbit"
#  framework: "Ruby"
#  service: "RabbitMQ"
#- name: "rubywithredis"
#  framework: "Ruby"
#  service: "Redis"
- name: "rubywithpostgresql"
  framework: "Ruby"
  service: "PostgreSQL"
- name: "rubywithrabbit"
  framework: "Ruby"
  service: "RabbitMQ"
- name: "rubywithredis"
  framework: "Ruby"
  service: "Redis"