---

background-color: '#005f78'
background-image: "url('/images/backgrounds/bubbles.png')"
font-family: 'QuickSand'
font-color: '#daf9ff'
background-repeat: 'false'
link:
  link: '#daf9ff'
  visited: '#ffffff'
  hover: '#007491'
  active: '#ffffff'

header:
  background-color: '#10101E'
  border-color: '#007491'
  font-color: '#daf9ff'
  link:
    link: '#daf9ff'
    visited: '#FFFFFF'
    hover: '#007491'
    active: '#FFFFFF'

footer:
  background-color: '#1C1c1c'
  border-color: '#007491'
  font-color: '#daf9ff'
  link:
    link: '#daf9ff'
    visited: '#00F3F9'
    hover: '#007491'
    active: '#098786'

breadcrumb:
  breadcrumb:
   color: '#daf9ff'
   font-size: '18px'
  breadcrumb-element:
    color: '#daf9ff'
    hover: '#ffffff'
    font-size: '18px'

error:
  border-color: '#D8000C'
  background-color: '#FFBABA'
  font-color: '#D8000C'
warning:
  border-color: '#ff9200'
  background-color: '#ffc373'
  font-color: '#a63a00'

button:
  border-color: '#cccccc'
  background-color: '#000000'
  font-color: '#FFFFFF'
  hover:
    border-color: '#000000'
    background-color: '#cccccc'
    font-color: '#FFFFFF'

image-buttons:
  24px:
    close: 'x.png'
    trash: 'trash_24px.png'
    edit: 'edit_24px.png'
    plus: 'plus_24px.png'
    minus: 'minus_24px.png'
    start: 'play_24px.png'
    stop: 'pause_24px.png'
  32px:
    money: 'money_sign_32.png'
    home: 'house.png'
    plus: 'plus_32px.png'
    edit: 'edit_32px.png'
    trash: 'trash_32px.png'
    undo: 'undo_sign_32.png'
    gear: 'gear_32px.png'
    key: 'key_32px.png'
    money: 'money_bag_sign_32.png'
  48px:
    money: 'money_sign_48.png'
    home: 'house.png'
    plus: 'plus_48px.png'
    edit: 'edit_48px.png'
    trash: 'trash_48px.png'
    undo: 'undo_sign_48.png'
    gear: 'gear_48px.png'
    key: 'key_48px.png'
    money: 'money_bag_sign_48.png'

tile-options:
  shadow-color: "#FFFFFF"
  opacity: 0.8

tiles:
  org:
    top:
      border-color: '#4573d5'
      background-color: '#1142aa'
      font-color: '#FFFFFF'
      link:
        link: '#FFFFFF'
        visited: '#FFFFFF'
        hover: '#FFFFFF'
        active: '#FFFFFF'
    left:
      border-color: '#6a48d7'
      background-color: '#3914af'
      font-color: '#FFFFFF'
      image-link: '/images/users_32px.png'
      link:
        link: '#FF00FF'
        visited: '#00F3F9'
        hover: '#326544'
        active: '#098786'
    right:
      border-color: '#259433'
      background-color: '#0acf00'
      font-color: '#FFFFFF'
      image-link: '/images/money_bag_32px.png'
      link:
        link: '#000000'
        visited: '#000000'
        hover: '#000000'
        active: '#000000'
  space:
    top:
      border-color: '#963fd5'
      background-color: '#680bab'
      font-color: '#FFFFFF'
      link:
        link: '#FFFFFF'
        visited: '#FFFFFF'
        hover: '#FFFFFF'
        active: '#FFFFFF'
    left:
      border-color: '#7147d7'
      background-color: '#4013af'
      font-color: '#FFFFFF'
      image-link: '/images/users_32px.png'
      link:
        link: '#FF00FF'
        visited: '#00F3F9'
        hover: '#326544'
        active: '#098786'
    right:
      border-color: '#36da82'
      background-color: '#00b454'
      font-color: '#FFFFFF'
      image-link: '/images/money_bag_32px.png'
      link:
        link: '#000000'
        visited: '#000000'
        hover: '#000000'
        active: '#000000'
  app:
    top:
      border-color: '#35d699'
      background-color: '#00ac6b'
      font-color: '#FFFFFF'
      link:
        link: '#FFFFFF'
        visited: '#FFFFFF'
        hover: '#FFFFFF'
        active: '#FFFFFF'
    left:
      border-color: '#39aecf'
      background-color: '#057d9f'
      font-color: '#FFFFFF'
      link:
        link: '#FF00FF'
        visited: '#00F3F9'
        hover: '#326544'
        active: '#098786'
    right:
      border-color: '#4ae83a'
      background-color: '#14d100'
      font-color: '#FFFFFF'
      link:
        link: '#FF00FF'
        visited: '#00F3F9'
        hover: '#326544'
        active: '#098786'
  service:
    top:
      border-color: '#4188d2'
      background-color: '#0d58a6'
      font-color: '#FFFFFF'
      link:
        link: '#FFFFFF'
        visited: '#FFFFFF'
        hover: '#FFFFFF'
        active: '#FFFFFF'
    left:
      border-color: '#6a48d7'
      background-color: '#3914af'
      font-color: '#FFFFFF'
      link:
        link: '#FF00FF'
        visited: '#00F3F9'
        hover: '#326544'
        active: '#098786'
    right:
      border-color: '#35d2ab'
      background-color: '#00a67c'
      font-color: '#FFFFFF'
      link:
        link: '#FF00FF'
        visited: '#00F3F9'
        hover: '#326544'
        active: '#098786'

square_tiles:
  owner:
    border-color: '#008500'
    background-color: '#008500'
    font-color: '#FFFFFF'
    image-link: '/images/members_icon.png'
    link:
      link: '#FFFFFF'
      visited: '#FFFFFF'
      hover: '#FFFFFF'
      active: '#FFFFFF'
  billing:
    border-color: '#a60000'
    background-color: '#a60000'
    font-color: '#FFFFFF'
    image-link: '/images/members_icon.png'
    link:
      link: '#FFFFFF'
      visited: '#FFFFFF'
      hover: '#FFFFFF'
      active: '#FFFFFF'
  developer:
    border-color: '#a60000'
    background-color: '#a60000'
    font-color: '#FFFFFF'
    image-link: '/images/members_icon.png'
    link:
      link: '#FFFFFF'
      visited: '#FFFFFF'
      hover: '#FFFFFF'
      active: '#FFFFFF'
  auditor:
    border-color: '#ff7400'
    background-color: '#ff7400'
    font-color: '#FFFFFF'
    image-link: '/images/members_icon.png'
    link:
      link: '#FFFFFF'
      visited: '#FFFFFF'
      hover: '#FFFFFF'
      active: '#FFFFFF'
  domain:
    border-color: '#1240ab'
    background-color: '#1240ab'
    font-color: '#FFFFFF'
    image-link: '/images/domains_icon_64px.png'
    link:
      link: '#FFFFFF'
      visited: '#FFFFFF'
      hover: '#FFFFFF'
      active: '#FFFFFF'
  route:
      border-color: '#1240ab'
      background-color: '#a60000'
      font-color: '#FFFFFF'
      image-link: '/images/domains_icon_64px.png'
      link:
        link: '#FFFFFF'
        visited: '#FFFFFF'
        hover: '#FFFFFF'
        active: '#FFFFFF'
  signup:
      border-color: '#1240ab'
      background-color: '#a60000'
      font-color: '#FFFFFF'
      image-link: '/images/members_icon.png'
      link:
        link: '#FFFFFF'
        visited: '#FFFFFF'
        hover: '#FFFFFF'
        active: '#FFFFFF'

rectangle_tile:
  app:
    border-color: '#8243d6'
    background-color: '#530fad'
    font-color: '#FFFFFF'
    link:
      link: '#FFFFFF'
      visited: '#FFFFFF'
      hover: '#FFFFFF'
      active: '#FFFFFF'


tab_menu:
  border-color: '#1c1c1c'
  font-color: '#daf9ff'
  selected-item-background: '#005f78'
  selected-item-foreground: '#daf9ff'
  link:
    link: '#000000'
    visited: '#000000'
    hover: '#000000'
    active: '#000000'

modal:
  footer:
      background-color: '#000000'
      font-color: '#FFFFFF'
      link:
        link: '#FF00FF'
        visited: '#00F3F9'
        hover: '#326544'
        active: '#098786'
  header:
      background-color: '#897668'
      font-color: '#FFFFFF'
      link:
        link: '#FF00FF'
        visited: '#00F3F9'
        hover: '#326544'
        active: '#098786'
  content:
      background-color: '#213452'
      font-color: '#FFFFFF'
      link:
        link: '#FF00FF'
        visited: '#00F3F9'
        hover: '#326544'
        active: '#098786'
  definitions:
    login:
      width: 350
    signup:
      width: 400
    logout:
      width: 320
    app_details:
      width: 900
    app_push:
      width: 900
    delete-confirmation:
      width: 500
    error-message:
      width: 450

controls:
  text:
      border-color: '#cccccc'
      background-color: '#000000'
      font-color: '#FFFFFF'

app_push:
  list:
    background-color: '#05296e'
    border-color: '#1144aa'
  tags:
    tag_color: '#028e98'
    text_color: '#00af64'
