login_error: Your username or password is incorrect!
signup_server_error: Something went wrong on the server!
signup_user_exists_error: The username already exists!
signup_create_organization_error: Could not create organization! (user was not created)
signup_error_password_size: Your password is to short(min 8 characters)!
signup_error_password_difference: Your password and confirm password don't match!
signup_error_email_format: Your email format is not accepted!
signup_error_first_name: Your need to enter your first name!
signup_error_last_name: Your need to enter your last name!
signup_error_recaptcha: Human challenge failed! Retype the code in the box!


change_username_error: Failed to update user data!
change_password_error: Failed to update user password!

username_error_first_name_size: The first name can not be blank!
username_error_last_name_size: The last name can not be blank!
username_error_password_size: Your password is to short(min 8 characters)!
username_error_password_difference: Your password and confirm password don't match!

organization_error_name_size: Organization name must be at least 4 characters long!
space_error_name_size: Space name must be at least 4 characters long!



create_organization_error: Failed to create Organization!
delete_organization_error: Failed to delete Organization!
update_organization_error: Failed to update the current Organization!

create_space_error: Failed to create Space!

delete_space_error: Failed to delete Space!
update_space_error: Failed to update the current Space!

create_domain_error: Failed to create this domain!
delete_domain_error: Failed to delete this doamin!







create_app_error: Failed to create this app!
delete_app_error: Failed to delete this app!
update_app_error: Failed to update this app properly!
start_app_error: App not started properly!
stop_app_error: App not stopped properly!
bind_service_error: Failed to bind this service to this app!
bind_uri_error: Failed to bind this uri to this app!
unbind_service_error: Failed to unbind this service from this app!
unbind_uri_error: Failed to unbind this uri from this app!


create_service_error: Failed to create Service!
service_error_name_size: Service name must be at least 4 characters long!
delete_service_error: Failed to delete this service!

add_user_error: Failed to add this User!
delete_user_error: Failed to delete this user!

create_route_error: Failed to create this Route!
delete_route_error: Failed to delete this Route!
