pid_filename: /tmp/uhuru_webui.pid
local_route: 10.0.0.90
port: 9494
dev-mode: true

webui:
  domain: "10.0.0.90:9494"
  activation_link_secret: "casnuugycasuygc12tddbhcb7"
  signup_user_password: "tHis1sth3def4ultuserpa55w0rd!!!"

cloudfoundry:
  cloud_controller_api: "http://api.uhurusoft.org"
  client_id: "cloud_controller"
  client_secret: "cc"
  cloud_controller_admin: "sre@vmware.com"
  cloud_controller_pass: "a"

uaa:
  uaa_api: "http://uaa.uhurusoft.org"

email:
  from: "postmaster@uhurusoftware.mailgun.org"
  from_alias: "Uhuru AppCloud"
  server: "smtp.gmail.com"
  port: 587
  user: "uhurusoft001@gmail.com"
  secret: "uhurusoft001"
  auth_method: :plain
  enable_tls: true

recaptcha:
  recaptcha_public_key: "6LcrstkSAAAAAIaBF-lyD5tpCQkqk8Z0uxgfsnRv"
  recaptcha_private_key: "6LcrstkSAAAAANnW08PSKQSOiC3r5PfHb02t-0OV-"


logging:
  level: debug
