
cloudfoundry:
  cloud-controller-api: "http://api3.ccng-dev.net"
  client-id: "cloud_controller"
  client-secret: "cc"

uaa:
  uaa-api: "http://uaa.ccng-dev.net"

uhuru:
  webui-port: 9494
  dev-mode: true

logger:
  path: "logs/main.log"