pid_filename: /tmp/uhuru_webui.pid
local_route: 10.0.0.1
port: 4567
dev-mode: true

cloud_controller_url: "http://api.ccng-dev.net"

uaa:
  url: "http://uaa.ccng-dev.net"
  client_id: "webui"
  client_secret: "webuisecret"

#cloud_controller_url: "http://api.uhurusoft.com"
#
#uaa:
#  url: "http://uaa.uhurusoft.com"
#  client_id: "webui"
#  client_secret: "5fcf640addd47f47f0a1b3a14e876d63"


contact:
  company: "Uhuru Software, Inc."
  address: "17530 NE Union Hill Road, Suite 120, Redmond, WA 98052, USA."
  phone: "+1 (425) 406-6383"
  email: "uhuru@uhurusoftware.com"
  company_link: "http://www.uhurusoftware.com"
  support_link: "http://uhurusoftware.zendesk.com"

recaptcha:
  use_recaptcha: false
  recaptcha_public_key: "6LfuXN4SAAAAAAVoUDfpUzxftBrpecXQSzTuKcZk"
  recaptcha_private_key: "6LfuXN4SAAAAAEuH--10s_lH_HMeYdjQtxha3UKd"

logging:
  level: debug
  #file: /var/vcap/sys/log/simple_webui/simple_webui.log

webui:
  page_title: "Uhuru WebUi"
  site_tab: "Uhuru"
  welcome_message: "Uhuru AppClound NG"
  copyright_message: "&copy; Copyright Uhuru Software 2012"

  #color_theme: "<%= properties.uhuru.simple_webui.color_theme || "simple_white" %>"
  #<% if properties.uhuru.simple_webui && properties.uhuru.webui.domain %>
  #domain: "<%= properties.uhuru.webui.domain %>"
  #<% else %>
  domain: "192.168.100.100"
  #<% end %>

  activation_link_secret: "terceseht"
  more_videos_link: 'http://support.uhurusoftware.com/forums/20507726-uhuru-knowledge-bases'
  guest_feedback_link: 'http://bit.ly/uhrbloglife'
  twitter_link: 'https://www.twitter.com/uhurusoftware'
  facebook_link: 'https://www.facebook.com/uhurusoftware'

  terms_of_services_link: 'http://uhurusoftware.com/tos'
  privacy_policy_link: 'http://uhurusoftware.com/privacy/'
  visual_studio_plugin_link: 'http://www.uhurucloud.com/tools/visualstudio'
  app_cloud_admin_link: "http://www.uhurucloud.com/tools/cloudadmin"
  command_line_link: "http://docs.cloudfoundry.com/tools/vmc/installing-vmc.html"
  eclipse_url: "http://docs.cloudfoundry.com/tools/STS/configuring-STS.html"

stripe:
  publishable_key: "pk_test_gRsPhGxpLivq7IsDPyuY9zs8"
  secret_key: "sk_test_fZOqxL3KHooewcpfplMZxVby"

monitoring:
  reports:
    half_of_day:
      resolution: 30
      resolution_unit: 'minutes'
      sample_count: 30
    last_day:
      resolution: 1
      resolution_unit: 'hours'
      sample_count: 30
    last_week:
      resolution: 6
      resolution_unit: 'hours'
      sample_count: 30
    last_month:
      resolution: 1
      resolution_unit: 'days'
      sample_count: 30
    last_year:
      resolution: 12
      resolution_unit: 'days'
      sample_count: 30
  vmc_executable_path: cf
  cloud_user: monitoring
  cloud_password: password1234!
  default_org: monitoring
  default_space: monitoring
  apps_domain: ["apps.ccng-dev.net"]
  email_to: ada.sescu@uhurusoftware.com
  sleep_after_app_push: 240
  pause_after_each_app: 1
  database:
    database: "monitoring"
    host: localhost
    port: 5432
    encoding: utf8
    username: postgres
    password: password1234!
    adapter: postgresql
    timeout: 2000
#    adapter: sqlite3
#    database: /tmp/monitoring.db
#    pool: 5
#    timeout: 5000
  components:
    deas:
      - name: dea
      - name: win_dea
    services:
      - name: mysql_node
        token: ec9743a4-6587-4356-8b9e-72d66b36a7f4
      - name: mongodb_node
        token: ec9743a4-6587-4356-8b9e-72d66b36a7f4
      - name: redis_node
        token: ec9743a4-6587-4356-8b9e-72d66b36a7f4
      - name: redis_node
        token: ec9743a4-6587-4356-8b9e-72d66b36a7f4
      - name: rabbit_node
        token: ec9743a4-6587-4356-8b9e-72d66b36a7f4
      - name: postgresql_node
        token: ec9743a4-6587-4356-8b9e-72d66b36a7f4
      - name: uhuru_tunnel_node
        token: ec9743a4-6587-4356-8b9e-72d66b36a7f4
      - name: uhurufs_node
        token: ec9743a4-6587-4356-8b9e-72d66b36a7f4
      - name: mssql_node
        token: ec9743a4-6587-4356-8b9e-72d66b36a7f4
  buildpacks:
    dotNet: https://github.com/stefanschneider/dummy-buildpack.git
    java: https://github.com/ramnivas/cloudfoundry-buildpack-java
    nodejs: https://github.com/cloudfoundry/heroku-buildpack-nodejs
    php: https://github.com/heroku/heroku-buildpack-php
    ruby: https://github.com/cloudfoundry/heroku-buildpack-ruby

email:
  from: "postmaster@uhurusoftware.mailgun.org"
  from_alias: "Uhuru Cloud"
  server: "smtp.mailgun.org"
  port: 587
  user: "postmaster@uhurusoftware.mailgun.org"
  secret: "4q899o1avzu3"
  auth_method: :login
  enable_tls: true
  registration_email: "
    <div>
    <h1>Uhuru Software Confirmation</h1>
    <p>Your account is ready to use. Please click the link bellow in order to continue and finish the signup process:</p>

    <a href='#ACTIVATION_LINK#' style='text-decoration: none; display: block;'>
      <div style='display: block; width: 200px; height: 200px; background-color: #603F3F; color: #ffffff; text-align: center; font-size: 24px;'>
        Finish<br /> registration
      </div>
    </a>

    <p>If you have not signup to uhuru cloud please ignore this email and the account will be removed automatically</p>
    <h3>The Uhuru team</h3>
    </div>
  "
  welcome_email: "
    <div>
      <h1>Welcome to Uhuru AppCloud</h1>
      <p>Thank you for joining the Uhuru community!</p>
      <h3>The Uhuru team</h3>
    </div>
  "