---
pid_filename: /tmp/uhuru_webui.pid
local_route: 10.0.0.1
port: 4567
dev_mode: true
cloud_controller_url: http://api.ccng-dev.net
message_bus_uri: nats://116e42690e023d88a208bff76eca54ca:8889dd351e08cc6f076bc02344320fbc@10.0.100.45:4222
bind_address: 10.0.102.200
uaa:
  url: http://uaa.ccng-dev.net
  client_id: webui
  client_secret: webuisecret
logging:
  level: debug
monitoring:
  reports:
    half_of_day:
      resolution: 30
      resolution_unit: minutes
      sample_count: 30
    last_day:
      resolution: 1
      resolution_unit: hours
      sample_count: 30
    last_week:
      resolution: 6
      resolution_unit: hours
      sample_count: 30
    last_month:
      resolution: 1
      resolution_unit: days
      sample_count: 30
    last_year:
      resolution: 12
      resolution_unit: days
      sample_count: 30
  vmc_executable_path: cf
  cloud_user: monitoring
  cloud_password: password1234!
  default_org: monitoring
  default_space: monitoring
  apps_domain:
  - apps.ccng-dev.net
  email_to: ada.sescu@uhurusoftware.com
  sleep_after_app_push: 240
  pause_after_each_app: 1
  database:
    database: monitoring
    host: localhost
    port: 5432
    encoding: utf8
    username: postgres
    password: password1234!
    adapter: postgresql
    timeout: 2000
  components:
    deas:
    - name: dea
    - name: win_dea
    services:
    - name: mysql_node
      token: ec9743a4-6587-4356-8b9e-72d66b36a7f4
    - name: mongodb_node
      token: ec9743a4-6587-4356-8b9e-72d66b36a7f4
    - name: redis_node
      token: ec9743a4-6587-4356-8b9e-72d66b36a7f4
    - name: redis_node
      token: ec9743a4-6587-4356-8b9e-72d66b36a7f4
    - name: rabbit_node
      token: ec9743a4-6587-4356-8b9e-72d66b36a7f4
    - name: postgresql_node
      token: ec9743a4-6587-4356-8b9e-72d66b36a7f4
    - name: uhuru_tunnel_node
      token: ec9743a4-6587-4356-8b9e-72d66b36a7f4
    - name: uhurufs_node
      token: ec9743a4-6587-4356-8b9e-72d66b36a7f4
    - name: mssql_node
      token: ec9743a4-6587-4356-8b9e-72d66b36a7f4
  buildpacks:
    dotNet: https://github.com/stefanschneider/dummy-buildpack.git
    java: https://github.com/ramnivas/cloudfoundry-buildpack-java
    nodejs: https://github.com/cloudfoundry/heroku-buildpack-nodejs
    php: https://github.com/heroku/heroku-buildpack-php
    ruby: https://github.com/cloudfoundry/heroku-buildpack-ruby
admin_config_file: /home/adauser/tmp/webui/admin-settings.yml
billing_data:
  provider: yml
  connection: /home/adauser/tmp/webui