---
pid_filename: /tmp/uhuru_webui.pid
local_route: 10.0.0.1
port: 4567
dev_mode: true
cloud_controller_url: "http://api.mitza.net"
message_bus_uri: nats://96fe61b95f6022d80e33ca58cfba0bc2:10d63f836c585dd3242cae2575dd7e58@10.0.100.45:4222
domain: www.rarunchiu.com
bind_address: 10.0.102.200
ccdb:
  host: "10.0.100.48"
  user: 'root'
  password: "8641926dc81377b150e1df77242dbe5d"
  port: 2544
  dbname: "ccdb_ng"
uaadb:
  host: "10.0.100.48"
  user: 'uaa'
  password: "8641926dc81377b150e1df77242dbe5d"
  port: 2544
  dbname: "uaa"

uaa:
  url: "http://uaa.mitza.net"
  client_id: "webui"
  client_secret: "15ea03c981afcc6ae95e04b71dc0ab3d"

logging:
  level: debug
  file: /tmp/uhuru_webui.log
monitoring:
  reports:
    half_of_day:
      resolution: 30
      resolution_unit: minutes
      sample_count: 30
    last_day:
      resolution: 1
      resolution_unit: hours
      sample_count: 30
    last_week:
      resolution: 6
      resolution_unit: hours
      sample_count: 30
    last_month:
      resolution: 1
      resolution_unit: days
      sample_count: 30
    last_year:
      resolution: 12
      resolution_unit: days
      sample_count: 30
  vmc_executable_path: bash -c "cf"
  cloud_user: monitoring
  cloud_password: "70ef08afbf99d921f4fc8e1ae5cbce36"
  default_org: monitoring
  default_space: monitoring
  apps_domain: ["apps.mitza.net"]
  email_to: "mihai.buzgau@uhurusoftware.com"
  sleep_after_app_push: 240
  pause_after_each_app: 1
  database:
    database: "monitoring"
    host: 10.0.100.48
    port: 2544
    encoding: utf8
    username: monitoring
    password: 8641926dc81377b150e1df77242dbe5d
    adapter: postgresql
    timeout: 2000
  components:
    deas:
    - name: "dea"
    - name: "win_dea"
    services:
    - name: mysql_node
      token: 28cb092d70db7f5720ee8bfe71037625
#    - name: mongodb_node <- not used yet
#      token:
    - name: redis_node
      token: 3204496267c2d50d6c99a4e0a66d79f4
    - name: rabbit_node
      token: b0f23985bdd3597895e9f6f445655b9c
    - name: postgresql_node
      token: cca0bec620aa400e9b7280d15944e285
#    - name: uhuru_tunnel_node <- not used yet
#      token:
#    - name: uhurufs_node <- not used yet
#      token:
    - name: mssql_node
      token: 9bdeed706a8f29725c227757a8795357

template_apps_dir: /tmp/template_apps
admin_config_file: /tmp/admin-settings.yml
billing_data:
  provider: yml
  connection: /tmp/billing_bindings.yml