pid_filename: /tmp/uhuru_webui.pid
local_route: 127.0.0.1
port: 9494
dev-mode: true

cloudfoundry:
  cloud_controller_api: "http://api3.ccng-dev.net"
  client_id: "cloud_controller"
  client_secret: "cc"

uaa:
  uaa_api: "http://uaa.ccng-dev.net"

logging:
  level: debug
