pid_filename: /tmp/uhuru_webui.pid
local_route: 192.168.1.9
port: 4567
dev-mode: true

cloudfoundry:
  cloud_controller_api: "http://api.ccng-dev.net"
  client_id: "cloud_controller"
  client_secret: "cc"
  cloud_controller_admin: "sre@vmware.com"
  cloud_controller_pass: "password1234!"

# todo: remove this and get the uaa endpoint from api.../info
uaa:
  uaa_api: "http://uaa.ccng-dev.net"

email:
  from: "postmaster@uhurusoftware.mailgun.org"
  from_alias: "Uhuru AppCloud"
  server: "smtp.gmail.com"
  port: 587
  user: "uhurusoft001@gmail.com"
  secret: "uhurusoft001"
  auth_method: :plain
  enable_tls: true

recaptcha:
  recaptcha_public_key: "6LcrstkSAAAAAIaBF-lyD5tpCQkqk8Z0uxgfsnRv"
  recaptcha_private_key: "6LcrstkSAAAAANnW08PSKQSOiC3r5PfHb02t-0OV-"


logging:
  level: debug

domains:
  - domain:
    url: "192.168.1.9:4567"
    page_title: "Uhuru WebUi"
    welcome_message: "PeakColo PaaS - powered by Uhuru"
  - domain:
    url: "127.0.0.1:4567"
    page_title: "Uhuru WebUi"
    welcome_message: "PeakColo PaaS - powered by Uhuru"
  - domain:
    url: "127.0.0.1:4567"
    page_title: "Uhuru WebUi"
    welcome_message: "PeakColo PaaS - powered by Uhuru Localhost"

webui:
  activation_link_secret: "terceseht"
  signup_user_password: "tHis1sth3def4ultuserpa55w0rd!!!"

quota_settings:
  billing_provider: chargify
  billing_provider_domain: uhurutestcloud
  auth_token: kQbDEn5os7NTX-TVv9GT
  division_factor: 256
