pid_filename: /tmp/uhuru_webui.pid
local_route: 10.0.0.90
port: 9494
dev-mode: true

cloudfoundry:
  cloud_controller_api: "http://api.uhurusoft.org"
  client_id: "cloud_controller"
  client_secret: "cc"
  cloud_controller_admin: "sre@vmware.com"
  cloud_controller_pass: "a"

uaa:
  uaa_api: "http://uaa.uhurusoft.org"

logging:
  level: debug
