---
applications:
- name: dotnetmysql
  memory: 128M
  instances: 1
  host: dotnetmysql
  domain: apps.ccng-dev.net
  path: .
  buildpack: https://github.com/stefanschneider/dummy-buildpack.git
  stack: iis75
  services:
    dotnetmysqlmonit:
      label: mysql
      provider: core
      version: '5.5'
      plan: free
